#!/bin/bash
# shopt -s inherit_errexit
# set -euo pipefail
# IFS=$'\n\t'
# set -x
export PS4='`[[ $? == 0 ]] || echo "\e[1;31;40m($?)\e[m\n "`:.$LINENO:'
die() { echo >&2 "$*"; exit 1; }
x() { set -x; "$@"; { set +x; } 2>/dev/null; }

[[ -z "${1:-}" ]] && {
    echo >&2 "Usage:
cd /tmp     # see TMPD below if you want to change it
$0 dir1 dir2
    OR
$0 dir1 a > /tmp/1
$0 dir2 b > /tmp/2
$0 dups

Output will open up in vim.  Lines will look like (tab-sep):
    339             337             a/personal      337             b/personal
    296             296             a/private       296             b/private
normally f1 <= f2, <= f4 (you can't have more matches than there are files!)
but if f1 > either f2 or f4, it means there are dups in that subdir
"
    exit
}

# ----------------------------------------------------------------------
export TMPD=/tmp

_b3() (
    cd $1
    find . -type f -print0 |
        xargs -0 b3sum -l 16 |
        sed -e 's/  /\t/' -e 's/\t\.\//\t'$2'\//' |
        sort
)

# ----------------------------------------------------------------------

if [[ -d ${2:-} ]]
then
    _b3 $1 a > /tmp/1
    _b3 $2 b > /tmp/2
elif [[ $2 =~ ^[ab]$ ]]
then
    _b3 $1 $2
    exit
elif [[ $1 == dups ]]
then
    :
else
    die '???'
fi


# ----------------------------------------------------------------------

join -j 1 -t $'\t' 1 2 | cut -f2,3 > 12
cp 12 12o
rm 12c

while grep -e '^a/..*'$'\t''b/.' < 12 > 12ab
do
    sed -e 's,/[^/]*\t,\t,' -e 's,/[^/]*$,,' < 12ab > 12
    cat 12 >> 12c
    # wc 12 12o 12c
    # vifm-pause
done

sort < 12c | uniq -c | sort -rn > 12cs
cat 12cs | perl -n -E '
    chomp;
    die "BAD $_" unless m(^ *(\d+) *(a.*)\t(b.*));
    $n = $1; $a = $2; $b = $3;
    BEGIN {
        local @ARGV = qw(1); @a = <>; chomp(@a);
        local @ARGV = qw(2); @b = <>; chomp(@b);
    }
    $ac = grep(/$a/, @a);
    $bc = grep(/$b/, @b);
    say "$n\t$ac\t$a\t$bc\t$b";
    # say "possible duplicates in above dir(s)" if $n > $ac or $n > $bc;
' > 12counts
vim -c 'set ts=16' 12counts
